### ISSUE TITLE
Only works on reload

### ISSUE THREAD

**Issue by nope3653** [somegenericdev/WYSIWYGTextEditor#1]
So my problem is that when I build my application and I go to the page where TextEditor is located I get this error:

![image](https://user-images.githubusercontent.com/25587279/145418708-de5f740b-c176-4374-8571-5766fe5c98cd.png)

But when I reload the page it works perfectly, could you please help me with this?

I am using: 
- visual studio 2022 
- blazor webassembly
- .NET 5.0
- WYSIWYGTextEditor 1.0.1

**Comment by somegenericdev** [comment]
This behavior is weird and it almost certainly doesn't depend on the component, the issue is probably on your side. What it means is basically that the component's Javascript file wasn't loaded the first time.
I wasn't able to reproduce the issue but I suspect that the cause might be that you're loading the component's Javascript files after blazor.webassembly.js. Try referencing them in this order in index.html. If you still encounter this issue afterwards you might want to upload a repo somewhere so that I can take a look at what's actually going on.
![immagine](https://user-images.githubusercontent.com/95114021/145652285-096bdbd7-768e-41fa-985c-1527a1e9c13f.png)

**Comment by nope3653** [comment]
Ah Thank very much, I solved the problem, I put the script refenrece in the head instead of the body, Thank you for the help
