### ISSUE TITLE
Loading JavaScript and CSS on demand 

### ISSUE THREAD

**Issue by SeanFeldman** [somegenericdev/WYSIWYGTextEditor#6]
The editor might be used on just a few specific pages but as of now, would load JavaScript and CSS files upon application startup.
Would be great if those resources would load when the control is rendered.

I wouldn’t mind helping if someone could point me to how Blazor handles on-demand resource loading.

**Comment by somegenericdev** [comment]
I think that's not possible with Blazor generally speaking, since Blazor is a SPA framework.
Apparently there [is a hacky way](https://stackoverflow.com/questions/58976579/blazor-server-load-js-scripts-only-on-certain-pages-not-on-all) to do what you're trying to do by manipulating the DOM with JS though.
As for CSS, Blazor supports [CSS isolation ](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/css-isolation?view=aspnetcore-6.0)(.razor.css files)

**Comment by SeanFeldman** [comment]
You're correct about Blazor. What I had in mind is the component loading its JavaScript. Similar to what is described [here](https://www.puresourcecode.com/dotnet/blazor/dynamically-add-javascript-from-blazor-components/).
